### ISSUE TITLE
$ID/$AUTH provision urls, regression

### ISSUE THREAD

**Issue by bjoto** [system-transparency/stboot#11]
In commit 7514d930cf23 ("rework stboot configuration") a regression is introduced; $ID/$AUTH is not replaced in the provisioning URL.

Further, the hostconfiguration printout is misspelled (Security and not Host) and weird:

```
[DEBUG] stboot: Security configuration: {
  "Version": 1,
  "IPAddrMode": 2,
  "HostIP": null,
  "DefaultGateway": null,
  "DNSServer": null,
  "NetworkInterface": null,
  "ProvisioningURLs": [
    {
      "Scheme": "http",
      "Opaque": "",
      "User": null,
      "Host": "10.0.2.10:8080",
      "Path": "/$ID/apan/$AUTH/latest.json",
      "RawPath": "",
      "ForceQuery": false,
      "RawQuery": "",
      "Fragment": "",
      "RawFragment": ""
    }
  ],
  "ID": "09B4D55443678F0128A39869FB060DA416BE2C984A986162C8DF20C3176DDC53",
  "Auth": "AD17ED02C848B7656A277F7E47A04F9AE05E5C48AF41F687093BACAC91782A7D"
}

```

**Comment by bjoto** [comment]
Or maybe not "weird", but different. :-)

**Comment by sylv-io** [comment]
Hi @bjoto.
Thanks, I'll examine this issue. :+1:

**Comment by sylv-io** [comment]
PR #12 should add support for ID/AUTH replacement again :)

I talked with @jensdrenhaus about the console output. It looks different because it prints the internal struct from the Host config instead of the JSON file.
He will rework it soon :)
