### ISSUE TITLE
Add optional field in `host_configuration.json` to store build time

### ISSUE THREAD

**Issue by sylv-io** [system-transparency/stboot#29]
Add a new field to `host_configuration.json` as an alternative to the `system_time_fix` file.

**Comment by MDr164** [comment]
The provision command in stmgr can already include a timestamp field in the host_configuration.json, I simply named it timestamp. https://github.com/system-transparency/stmgr/blob/main/provision/parser.go#L25

**Comment by jensdrenhaus** [comment]
Done
