### ISSUE TITLE
Add flag to control source of HostCfg

### ISSUE THREAD

**Issue by jensdrenhaus** [system-transparency/stboot#41]
Default: stboot loads HostCfg from `/etc/host_configuration.json` at the initramfs (same as security configuration)

Add flags `--host-config` and `--host-config-name`
`--host-config=initramfs` (default) load from initramfs with default path
--host-config=efivar load from efivarfs with default variable name
`--host-config=legacy` load from partition with label "STBOOT" with default path

`--host-config-name=<_filepath or variable name_>`

Examples:
no flag provided: Load from `/etc/host_configuration.json` at the initramfs
`--host-config=initramfs`  `--host-config-name=custom/path/cfg.json` : Load from initramfs but override default path
`--host-config=efivar`  Load from efivars using a default ID/var name
`--host-config=efivar` `--host-config-name=STYADDA-d736a263-c838-4702-9df4-50134ad8a636` : Load from efivars but using custim efivar ID and name

**Comment by sylv-io** [comment]
Proposal:

Instead of having two separate flags to determine the location of host configuration, use a single flag in this structure:
`--host-config=<mode>` or `--host-config=<mode>:<location>`

Examples:
initramfs: `--host-config=initramfs:/path/to/hostconfig`
efivars: `--host-config=efivar:STDATA-d736a263-c838-4702-9df4-50134ad8a636`
storage: `--host-config=stdata:/path/to/hostconfig`

Default mode is `initramfs` and each mode has its default location.

**Comment by sylv-io** [comment]
Update:

After thinking about it for a while, I think there is a simpler solution for this problem.
There are two ways how host-configuration is store, as file or in an efivar.
Right now STBOOT partition has its mountpoint at `/boot` (and STDATA at `/data`). We could add logic to only mount them if explicit required (e.g. local boot mode or host configuration is located there)

So i would propose a structure like this:

in initramfs:
`--host-config=/path/to/host_configuration.json`
in STBOOT (aka. legacy):
`--host-config=/boot/path/to/host_configuration.json`
in STDATA:
`--host-config=/data/path/to/host_configuration.json`
in an efivar:
`--host-config=efivar:STDATA-d736a263-c838-4702-9df4-50134ad8a636`

We could even extend this configuration to other files like security_config.json, https_root.pem etc.

This would make it easier to understand and better configurable, and remove a lot of hard-coded specifications in other use cases.

**Comment by MDr164** [comment]
I think the last proposal makes it the easiest for the user to use stboot. If we internally get the conditional mounting right we could then abstract some work away from the user.

**Comment by jensdrenhaus** [comment]
Agree on 
`--host-config=/path/to/host_configuration.json` for initrmafs
`--host-config=efivar:STDATA-d736a263-c838-4702-9df4-50134ad8a636` for efivar
I also like the idea about taking the info from the path whether we should mount something, but lets discuss this later when talking about partitions in general and a `--host-config=lagacy` for the old behavior (partition with label STBOOT, etc.)

**Comment by jensdrenhaus** [comment]
Done in #47
