### ISSUE TITLE
Suggestion to add ability to sort STpackage servers by initial ping

### ISSUE THREAD

**Issue by jbjorkang** [system-transparency/stboot#81]
As it stands now we have multiple STpackage servers listed under stpackage.domain.com, without anycasting we have to rely on a basic DNS round-robin.

Suggestion is to add the ability to ping each IP and return the fastest result, using that as the STpackage server to download an OS PKG from.

For example this one-liner does a rudimentary ping towards a remote server, returning the latency:
```
for ip in $(dig +short stpackage.domain.com); do ping -c 1 $ip | grep time | head -n1 | awk '{ print $7 }' | tr -d 'time='; done
10.0
5.94 <-- use this one for this run
```

**Comment by jensdrenhaus** [comment]
https://git.glasklar.is/system-transparency/core/stboot/-/tree/main/

**Comment by jbjorkang** [comment]
This is completed?
