### ISSUE TITLE
stmanager unable to parse RSA key

### ISSUE THREAD

**Issue by ln5** [system-transparency/stboot#9]
`$ stmanager sign --key=keys/signing_keys/signing-key-new.key --cert=keys/signing_keys/signing-key-new.cert out/os-packages/st0.zip`
`stmanager: os package sign: parse PKCS8: x509: failed to parse private key (use ParsePKCS1PrivateKey instead for this key format)`
`$ head -1 keys/signing_keys/signing-key-new.key`
`-----BEGIN RSA PRIVATE KEY-----`

**Comment by ln5** [comment]
```openssl pkcs8 -topk8 -nocrypt -in key.key -out key.p8.pem

**Comment by bjoto** [comment]
@ln5 Is this still relevant?

**Comment by bjoto** [comment]
Closing.
